### ISSUE TITLE
safari版本获取有问题

### ISSUE THREAD

**Issue by mkc0423** [D-xuanmo/browser-info#6]
看代码是拿了系统版本，但实际上并不是系统版本

**Comment by D-xuanmo** [comment]
@mkc0423 可以提供具体的情况吗？

**Comment by mkc0423** [comment]
> @mkc0423 可以提供具体的情况吗？

例如

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML\, like Gecko) Chrome/87.0.4280.88 Safari/537.36
--


拿到的是10.15，而不是87.0

**Comment by D-xuanmo** [comment]
@mkc0423 这个10.15是系统版本，浏览器版本才是87.0，我用你提供的这个信息打印的结果是以下内容：
```js
{
  systemName: 'Mac', // 系统平台名称
  systemVersion: '10.15.6', // 系统版本号
  browserName: 'Chrome', // 浏览器中文名
  browserVersion: '87.0', // 浏览器版本号
  browserEnName: 'Chrome' // 浏览器英文名
}
```
